### ISSUE TITLE
Unspported media

### ISSUE THREAD

**Issue by gibsonjimoliver** [tsaridas/stremio-docker#13]
I keep getting an "unsupported media" playback error when trying to play files using the web player. I have successfully connected to the service using HTTPS.

The specific error is "Video is not supported" when using the V5 client (web.stremio.com).

When using the V4.4 client and hosted web player, the errror is "Playback error, please try again".

**Comment by tsaridas** [comment]
I assume you setup the streaming server and it shows working ? logs from the docker container ?

**Comment by gibsonjimoliver** [comment]
Streaming server is running and the client has successfully connected according to the Stremio settings (i.e. it says 'online' in the settings view).

Looking at the Docker logs, there does appear to be an error that crops up everytime I hit play. See below:

> -> GET /hlsv2/probe?mediaURL=https%3A%2F%2Ftorrentio.strem.fun%2Frealdebrid%2FJWRCH4RLAYJSTA2GJ5V5MQMSIAKQ7ZYKMCWZ6KJRBGGFPDA3PEQA%2F8ee79a6871040119cb300a15c7e4189e245a7c22%2Fnull%2F0%2FSociety.of.the.Snow.2023.MULTi.SDR.2160p.WEB.H265-FW 
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/srv/stremio-server/server.js:29830:156)
    at Object.onceWrapper (node:events:632:26)
    at EventEmitter.emit (node:events:517:28)
    at EventEmitter.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/srv/stremio-server/server.js:65184:37)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
-> HEAD /hlsv2/0fc7f43ae8b5c90b87e1657e659b37c8/master.m3u8?mediaURL=https%3A%2F%2Ftorrentio.strem.fun%2Frealdebrid%2FJWRCH4RLAYJSTA2GJ5V5MQMSIAKQ7ZYKMCWZ6KJRBGGFPDA3PEQA%2F8ee79a6871040119cb300a15c7e4189e245a7c22%2Fnull%2F0%2FSociety.of.the.Snow.2023.MULTi.SDR.2160p.WEB.H265-FW&videoCodecs=h264&videoCodecs=h265&videoCodecs=hevc&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=2 
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/srv/stremio-server/server.js:29830:156)
    at Object.onceWrapper (node:events:632:26)
    at EventEmitter.emit (node:events:517:28)
    at EventEmitter.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/srv/stremio-server/server.js:65184:37)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
-> GET /opensubHash?videoUrl=https%3A%2F%2Ftorrentio.strem.fun%2Frealdebrid%2FJWRCH4RLAYJSTA2GJ5V5MQMSIAKQ7ZYKMCWZ6KJRBGGFPDA3PEQA%2F8ee79a6871040119cb300a15c7e4189e245a7c22%2Fnull%2F0%2FSociety.of.the.Snow.2023.MULTi.SDR.2160p.WEB.H265-FW 
-> GET /hlsv2/0fc7f43ae8b5c90b87e1657e659b37c8/master.m3u8?mediaURL=https%3A%2F%2Ftorrentio.strem.fun%2Frealdebrid%2FJWRCH4RLAYJSTA2GJ5V5MQMSIAKQ7ZYKMCWZ6KJRBGGFPDA3PEQA%2F8ee79a6871040119cb300a15c7e4189e245a7c22%2Fnull%2F0%2FSociety.of.the.Snow.2023.MULTi.SDR.2160p.WEB.H265-FW&videoCodecs=h264&videoCodecs=h265&videoCodecs=hevc&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=2 bytes=0-
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/srv/stremio-server/server.js:29830:156)
    at Object.onceWrapper (node:events:632:26)
    at EventEmitter.emit (node:events:517:28)
    at EventEmitter.emit (node:domain:489:12)
    at ChildProcess.<anonymous> (/srv/stremio-server/server.js:65184:37)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)

**Comment by tsaridas** [comment]
maybe your addon is not working correctly. Try using another addon ? restart server before doing that.

**Comment by gibsonjimoliver** [comment]
Thank you. By removing RealDebrid from Torrentio, I managed to get playback working.

I believe the issue is that, with RealDebrid enabled, the browser client tries to stream directly from the RealDebrid link rather than stream using the docker streaming service. 

When just streaming public torrents using Torrentio, the functionality works as intended and the streaming link is the IP address of the docker service.

**Comment by tsaridas** [comment]
Honestly I haven't tried this with RealDebrid as I don't need it but I guess it shouldn't be an issue.
