### ISSUE TITLE
player not working

### ISSUE THREAD

**Issue by notkudu** [tsaridas/stremio-docker#19]
I installed the docker image and setup the streming server to my Lan IP and it's showing that the server is online

I installed Torrentio addon but when ever I want to stream the player error out with "Video is not supported".
I can use an extrnal player with m3u and vlc just fine.

I get this error in the logs when I try to play anything:
```
SSDP error: {
  type: 'ssdp',
  error: {
    type: 'send',
    error: Error: send EPERM 239.255.255.250:1900
        at doSend (node:dgram:718:16)
        at defaultTriggerAsyncIdScope (node:internal/async_hooks:462:18)
        at afterDns (node:dgram:664:5)
        at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
      errno: -1,
      code: 'EPERM',
      syscall: 'send',
      address: '239.255.255.250',
      port: 1900
    }
  }
}
```

**Comment by tsaridas** [comment]
try setting CASTING_DISABLED=1

**Comment by notkudu** [comment]
well... now I am getting this error instead
```
-> GET /settings 
-> GET /casting 
-> GET /network-info 
[2024-04-06T22:42:31.884Z]  "GET /500c80df277f2f2eaf0df1fd6c451aad905bb5cf/images/stremio_symbol.png" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
-> GET /device-info 
hls-converter - Initiating tests for hardware accelerated transcoding support, possible options: qsv-linux,nvenc-linux,vaapi-renderD128
hls-converter - Testing video hw accel for profile: qsv-linux
[2024-04-06T22:42:31.899Z]  "GET /500c80df277f2f2eaf0df1fd6c451aad905bb5cf/fonts/PlusJakartaSans.ttf" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
-> GET /hlsv2/11470-qsv-linux-video-hevc.mkv/video0.m3u8?mediaURL=http%3A%2F%2F127.0.0.1%3A11470%2Fsamples%2Fhevc.mkv&profile=qsv-linux&maxWidth=1200 
-> GET /samples/hevc.mkv bytes=0-
-> GET /samples/hevc.mkv 
Error: stream ended
    at Socket.onFinished (/srv/stremio-server/server.js:76499:145)
    at Socket.<anonymous> (node:internal/util:530:12)
    at Socket.onfinish (node:internal/streams/end-of-stream:113:16)
    at Socket.emit (node:events:517:28)
    at finish (node:internal/streams/writable:748:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
-> GET /hlsv2/11470-qsv-linux-video-hevc.mkv/destroy 
hls-converter 11470-qsv-linux-video-hevc.mkv has been requested to be destroyed
hls-converter 11470-qsv-linux-video-hevc.mkv destoyed
hls-converter - Tests failed for [video] hw accel profile: qsv-linux
hls-converter - Some tests failed for hw accel profile: qsv-linux
hls-converter - Testing video hw accel for profile: nvenc-linux
-> GET /hlsv2/11470-nvenc-linux-video-hevc.mkv/video0.m3u8?mediaURL=http%3A%2F%2F127.0.0.1%3A11470%2Fsamples%2Fhevc.mkv&profile=nvenc-linux&maxWidth=1200 
hls-converter 11470-qsv-linux-video-hevc.mkv will be destroyed due to passing concurrency of 1
-> GET /samples/hevc.mkv 
Error: stream ended
    at Socket.onFinished (/srv/stremio-server/server.js:76499:145)
    at Socket.<anonymous> (node:internal/util:530:12)
    at Socket.onfinish (node:internal/streams/end-of-stream:113:16)
    at Socket.emit (node:events:517:28)
    at finish (node:internal/streams/writable:748:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
-> GET /hlsv2/11470-nvenc-linux-video-hevc.mkv/destroy 
hls-converter 11470-nvenc-linux-video-hevc.mkv has been requested to be destroyed
hls-converter 11470-nvenc-linux-video-hevc.mkv destoyed
hls-converter - Tests failed for [video] hw accel profile: nvenc-linux
hls-converter - Some tests failed for hw accel profile: nvenc-linux
hls-converter - Testing video hw accel for profile: vaapi-renderD128
-> GET /hlsv2/11470-vaapi-renderD128-video-hevc.mkv/video0.m3u8?mediaURL=http%3A%2F%2F127.0.0.1%3A11470%2Fsamples%2Fhevc.mkv&profile=vaapi-renderD128&maxWidth=1200 
hls-converter 11470-nvenc-linux-video-hevc.mkv will be destroyed due to passing concurrency of 1
-> GET /samples/hevc.mkv 
Error: stream ended
    at Socket.onFinished (/srv/stremio-server/server.js:76499:145)
    at Socket.<anonymous> (node:internal/util:530:12)
    at Socket.onfinish (node:internal/streams/end-of-stream:113:16)
    at Socket.emit (node:events:517:28)
    at finish (node:internal/streams/writable:748:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
-> GET /hlsv2/11470-vaapi-renderD128-video-hevc.mkv/destroy 
hls-converter 11470-vaapi-renderD128-video-hevc.mkv has been requested to be destroyed
hls-converter 11470-vaapi-renderD128-video-hevc.mkv destoyed
hls-converter - Tests failed for [video] hw accel profile: vaapi-renderD128
hls-converter - Some tests failed for hw accel profile: vaapi-renderD128
hls-converter - Tests for hardware accelerated transcoding finished, no viable acceleration profiles detected
-> OPTIONS /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
-> GET /hlsv2/probe?mediaURL=http%3A%2F%2F10.0.0.99%3A11470%2F41fdd775a1abf62b707e349f9507a08762dd5828%2F0 
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/srv/stremio-server/server.js:35359:156)
    at Object.onceWrapper (node:events:632:26)
    at EventEmitter.emit (node:events:517:28)
    at ChildProcess.<anonymous> (/srv/stremio-server/server.js:72828:37)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
-> HEAD /41fdd775a1abf62b707e349f9507a08762dd5828/0 
Engine created for 41fdd775a1abf62b707e349f9507a08762dd5828
Resizing cache size to 2048MB from 346MB by deleting 0 files
Resizing cache size to 2048MB from 346MB by deleting 0 files
-> HEAD /hlsv2/3586bfe07c9e39c272f27ab543409af9/master.m3u8?mediaURL=http%3A%2F%2F10.0.0.99%3A11470%2F41fdd775a1abf62b707e349f9507a08762dd5828%2F0&videoCodecs=h264&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=2 
hls-converter 11470-vaapi-renderD128-video-hevc.mkv will be destroyed due to passing concurrency of 1
-> GET /opensubHash?videoUrl=http%3A%2F%2F10.0.0.99%3A11470%2F41fdd775a1abf62b707e349f9507a08762dd5828%2F0 
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/srv/stremio-server/server.js:35359:156)
    at Object.onceWrapper (node:events:632:26)
    at EventEmitter.emit (node:events:517:28)
    at ChildProcess.<anonymous> (/srv/stremio-server/server.js:72828:37)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
-> GET /hlsv2/3586bfe07c9e39c272f27ab543409af9/master.m3u8?mediaURL=http%3A%2F%2F10.0.0.99%3A11470%2F41fdd775a1abf62b707e349f9507a08762dd5828%2F0&videoCodecs=h264&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=2 bytes=0-
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/srv/stremio-server/server.js:35359:156)
    at Object.onceWrapper (node:events:632:26)
    at EventEmitter.emit (node:events:517:28)
    at ChildProcess.<anonymous> (/srv/stremio-server/server.js:72828:37)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
-> GET /41fdd775a1abf62b707e349f9507a08762dd5828/0/stats.json 
```

**Comment by tsaridas** [comment]
seems like an exception on the server side. This is not my code. They recently upgraded the server version. maybe you can try to use an older version of the docker image in docker hub ? https://hub.docker.com/r/tsaridas/stremio-docker

the latest should be the same as v1.1.9 maybe try v1.1.4.

**Comment by notkudu** [comment]
> seems like an exception on the server side. This is not my code. They recently upgraded the server version. maybe you can try to use an older version of the docker image in docker hub ? https://hub.docker.com/r/tsaridas/stremio-docker
> 
> the latest should be the same as v1.1.9 maybe try v1.1.4.

hey, thanks for the suggestion but I am still geting the same error as above with v1.1.4

I am using gluetun to rout the container over a vpn, I will tray without it and see if it's working

**Comment by notkudu** [comment]
I just test it and worked without gluetun on the latest version but I can't run it without a vpn, any suggestion regarding?

**Comment by tsaridas** [comment]
you dont have to use vpn if you pay for some service that downloads torrents and send the http link to stremio. I'll leave it up to you to research which one to choose. 

im not sure why the vpn doesnt work .. maybe avoid routing local ips ? you need to troubleshoot .. 

in general, if this is too technical for you i would stay away from trying to install this via docker and setup vpn. stremio offers normal installations.
