### ISSUE TITLE
Version 4.20.11

### ISSUE THREAD

**Issue by marty-macfly** [tsaridas/stremio-docker#55]
Hello,

I've seen that your image is still using version 4.20.8 of stremio server, version 4.2011 has been released are you planing to upgrade the image to that version ?

Regards,

**Comment by tsaridas** [comment]
hi, we take the server version from stremio-shell 

```
https://github.com/Stremio/stremio-shell/blob/master/server-url.txt
```

I am aware that server version has changed but I see no reason to update and sync with latest since container is working fine. There have been issues with updating server version to latest so would rather wait for them updating it in shell which should be more stable. Do you have any issues with current server version ?

**Comment by marty-macfly** [comment]
Thanks for your reply.

No not at all, It's working properly, I've seen that they have release their docker version of server with version 4.20.9, 4.20.10 and 4.20.11 and I was wondering why you don't bump yours.

I've tried to use the version upper than 4.20.8 and I'm also facing issues, so your choice seems to be the wise one :-) I've got another question (I'm sorry because it is may be not the proper place to ask them ? Should I use the discussions section ?)

I was having a look to [stremio-web-service-run.sh](https://github.com/tsaridas/stremio-docker/blob/main/stremio-web-service-run.sh#L8) and was wondering why you are setting ` self.proxyStreamsEnabled = false` what is the purpose of that configuration ?

**Comment by tsaridas** [comment]
> I was having a look to [stremio-web-service-run.sh](https://github.com/tsaridas/stremio-docker/blob/main/stremio-web-service-run.sh#L8) and was wondering why you are setting ` self.proxyStreamsEnabled = false` what is the purpose of that configuration ?

It was an issue with web player and server.js not having that config. it should probably be resolved but since we had a non working container at the time I decided to set it manually to server.js. I think issue should be fixed to latest version of the server but too lazy to test and remove the config. Will remove it when new server version is released and everything works ok. 

I did try latest version 4.20.11 and ran without issues. Not sure what your issue was.

**Comment by tsaridas** [comment]
> When I'm moving to version 4.20.11, streaming doesn't start, plugin doesn't find peer, and never download anything. When reverting to 4.20.8 everything start in seconds.

seems to work fine for me. tested again. you have a specific example ?

**Comment by marty-macfly** [comment]
When everything is working properly (so with verison 4.20.8)

I've got following log on server:

```
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /hlsv2/probe?mediaURL=https%3A%2F%2Fmydomain.com%2F353dc02e86f1110fdd40b8bfdebacf534a9595c8%2F0
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/srv/stremio-server/server.js:35360:156)
    at Object.onceWrapper (node:events:632:26)
    at EventEmitter.emit (node:events:517:28)
    at ChildProcess.<anonymous> (/srv/stremio-server/server.js:72829:37)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
-> HEAD /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0
Engine created for 353dc02e86f1110fdd40b8bfdebacf534a9595c8
Resizing cache size to 10240MB from 9670MB by deleting 0 files
-> HEAD /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0
-> GET /opensubHash?videoUrl=https%3A%2F%2Fmydomain.com%2F353dc02e86f1110fdd40b8bfdebacf534a9595c8%2F0
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0 bytes=0-
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0 bytes=5146804224-
-> GET /subtitles.vtt?from=https%3A%2F%2Fsubs5.strem.io%2Fen%2Fdownload%2Fsubencoding-stremio-utf8%2Fsrc-api%2Ffile%2F1958162882
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
hls-converter ca46b537e6e8f0876a109db2c78587da is inactive, destroying it
hls-converter ca46b537e6e8f0876a109db2c78587da destoyed
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
Engine 353dc02e86f1110fdd40b8bfdebacf534a9595c8 is inactive, destroying it
Engine 353dc02e86f1110fdd40b8bfdebacf534a9595c8 destroyed
```

And on web interface I can see:

![image](https://github.com/user-attachments/assets/efe04ef6-d6b5-42a8-b67f-e70d5eade8a3)

When moving to verison 4.20.11:

```
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /hlsv2/probe?mediaURL=https%3A%2F%2Fmydomain.com%2F353dc02e86f1110fdd40b8bfdebacf534a9595c8%2F0
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/stremio/server.js:35408:156)
    at Object.onceWrapper (events.js:520:26)
    at EventEmitter.emit (events.js:400:28)
    at ChildProcess.<anonymous> (/stremio/server.js:73861:37)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
-> HEAD /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> HEAD /hlsv2/c8412ef10be68ab9efb5b4c2c7160aaa/master.m3u8?mediaURL=https%3A%2F%2Fmydomain.com%2F353dc02e86f1110fdd40b8bfdebacf534a9595c8%2F0&videoCodecs=h264&videoCodecs=vp9&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=2
-> GET /opensubHash?videoUrl=https%3A%2F%2Fmydomain.com%2F353dc02e86f1110fdd40b8bfdebacf534a9595c8%2F0
-> GET /subtitles.vtt?from=https%3A%2F%2Fsubs5.strem.io%2Fen%2Fdownload%2Fsubencoding-stremio-utf8%2Fsrc-api%2Ffile%2F1958162882
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/stremio/server.js:35408:156)
    at Object.onceWrapper (events.js:520:26)
    at EventEmitter.emit (events.js:400:28)
    at ChildProcess.<anonymous> (/stremio/server.js:73861:37)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)
-> GET /hlsv2/c8412ef10be68ab9efb5b4c2c7160aaa/master.m3u8?mediaURL=https%3A%2F%2Fmydomain.com%2F353dc02e86f1110fdd40b8bfdebacf534a9595c8%2F0&videoCodecs=h264&videoCodecs=vp9&audioCodecs=aac&audioCodecs=mp3&audioCodecs=opus&maxAudioChannels=2 bytes=0-
Error: Probe process exited with code: 1
    at EventEmitter.<anonymous> (/stremio/server.js:35408:156)
    at Object.onceWrapper (events.js:520:26)
    at EventEmitter.emit (events.js:400:28)
    at ChildProcess.<anonymous> (/stremio/server.js:73861:37)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Socket.<anonymous> (internal/child_process.js:446:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12)
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
-> GET /353dc02e86f1110fdd40b8bfdebacf534a9595c8/0/stats.json
```

![image](https://github.com/user-attachments/assets/c20a8c44-ad0a-4646-929a-6bf5220a9142)

**Comment by tsaridas** [comment]
I'm guessing mydomain.com is something custom to you and you changed it so that it doesn't show ?

don't think I can help

**Comment by marty-macfly** [comment]
Yes, that's right, I've just change the domain name. No worries thanks for your help
